name: CI

on:
  pull_request:
    branches: [master]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Verify conventional commits
        uses: taskmedia/action-conventional-commits@v1.1.0
        with:
          types: "feat|fix|ci|docs|perf|refactor|build|test|chore"

      - uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
